# Generated by Django 5.0.4 on 2024-04-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayname', models.CharField(max_length=500)),
                ('displayversion', models.CharField(max_length=500)),
                ('installdate', models.DateTimeField(blank=True, null=True)),
                ('installedfor', models.CharField(max_length=200)),
                ('installlocation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='datacompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
