# Generated by Django 5.0.4 on 2024-04-29 21:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_programa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='upload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
