# Generated by Django 5.0.4 on 2024-05-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_programa_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='servername',
            field=models.TextField(),
        ),
    ]
